### ISSUE TITLE
howto polyline?

### ISSUE THREAD

**Issue by nortikin** [reclosedev/pyautocad#24]
>>> m.AddPolyline((APoint(0,0),APoint(-1000,-1000),APoint(5000,-5000)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\P1\AppData\Local\Programs\Python\Python36\lib\site-packages\comtypes\client\lazybind.py", line 182, in caller
    return self._comobj._invoke(descr.memid, descr.invkind, 0, *args)
  File "C:\Users\P1\AppData\Local\Programs\Python\Python36\lib\site-packages\comtypes\automation.py", line 729, in _invoke
    dp, var, None, argerr)
_ctypes.COMError: (-2147352567, 'Ошибка.', (None, None, None, 0, None))

**Comment by FrancoTonutti** [comment]
```python
from pyautocad import Autocad
import array

acad = Autocad(create_if_not_exists=True)

points_2d = [0, 0, 1, 1, 2, 1]
points_double = array.array("d", points_2d)
acad.model.AddLightWeightPolyline(points_double)

points_3d = [0, 0, 0, 1, 1, 0, 2, 1, 0]
points_double = array.array("d", points_3d)
acad.model.AddPolyline(points_double)
```

**Comment by iNakel** [comment]
> ```python
> from pyautocad import Autocad
> import array
> 
> acad = Autocad(create_if_not_exists=True)
> 
> points_2d = [0, 0, 1, 1, 2, 1]
> points_double = array.array("d", points_2d)
> acad.model.AddLightWeightPolyline(points_double)
> 
> points_3d = [0, 0, 0, 1, 1, 0, 2, 1, 0]
> points_double = array.array("d", points_3d)
> acad.model.AddPolyline(points_double)
> ```

the result is a 2D Polyline... and not a 3D Polyline... ¿is it possible to get it 3D?

**Comment by better319** [comment]
in the end how to choice the “closed”

**Comment by better319** [comment]
in the end how to choice the “closed”，when finish draw

**Comment by CEXT-Dan** [comment]
> in the end how to choice the “closed”，when finish draw

use Closed..
https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-5A604B98-B6DE-42C3-97D9-98B8CAEBB507

```python
from pyautocad import Autocad
import array

acad = Autocad(create_if_not_exists=True)

points_3d = [0, 0, 0, 1, 1, 0, 2, 1, 0]
points_double = array.array("d", points_3d)
pline = acad.model.AddPolyline(points_double)
pline.Closed = True

```
