### ISSUE TITLE
Pyautocad: error using pyautocad library on windows (python 3.8)

### ISSUE THREAD

**Issue by denissanga** [reclosedev/pyautocad#37]
Good moning,

I’m trying using pyautocad library in python 3.8 on windows with the following example code taken from a tutorial:
`import pyautocad 
acad = pyautocad.Autocad() 
print(acad.doc.Name) 
from pyautocad 
import APoint 
point1 = APoint(100.0,100.0) 
circle1 = acad.model.AddCircle(point1,100) 
circle1.Color = 10 print("current layer: " + str(circle1.Layer)) 
print("current linetype: " + str(circle1.Linetype)) 
print("current linetype scale: " + str(circle1.LinetypeScale))
print("current line weight: " + str(circle1.Lineweight)) 
print("current thickness: " + str(circle1.Thickness)) 
print("current material:" + str(circle1.Material)) 
circle1.Layer = "circles" circle1.Color = 256 
circle2 = acad.model.AddCircle(APoint(200.0,200.0),100) 
circle3 = acad.model.AddCircle(APoint(300.0,300.0),100) 
for obj in acad.iter_objects(): 
     print(obj)`

But I obtain the following error and I don’t understand how to solve it:

`python pyAutocadTest.py Traceback (most recent call last): File "pyAutocadTest.py", line 6, in <module> print(acad.doc.Name) File "C:\Users\3bMeteo\anaconda3\lib\site-packages\pyautocad\api.py", line 74, in doc return self.app.ActiveDocument File "C:\Users\3bMeteo\anaconda3\lib\site-packages\pyautocad\api.py", line 63, in app self._app = comtypes.client.GetActiveObject('AutoCAD.Application', dynamic=True) File "C:\Users\3bMeteo\anaconda3\lib\site-packages\comtypes\client\__init__.py", line 180, in GetActiveObject obj = comtypes.GetActiveObject(clsid, interface=interface) File "C:\Users\3bMeteo\anaconda3\lib\site-packages\comtypes\__init__.py", line 1245, in GetActiveObject oledll.oleaut32.GetActiveObject(byref(clsid), None, byref(p)) File "_ctypes/callproc.c", line 948, in GetResult OSError: [WinError -2147221021] Operazione non disponibile`

Can I ask if someone has a solution?

Thank you in advance

Best Regard

**Comment by 13537891894** [comment]
I also encountered the same issue. Have you solved it?
