### ISSUE TITLE
can not read attributes from block reference

### ISSUE THREAD

**Issue by thengineer** [reclosedev/pyautocad#6]
I'm trying to read block attributes:

```
from pyautocad import Autocad
acad =  Autocad()       
```

Reading other properties works fine:

```
In [89]: b.InsertionPoint
Out[89]: (3764.4951495785735, 745.3710248379173, 0.0)
```

However, when I want to query the attributes (which I'm actually interested in), I get an error message:

```
In [88]: b.GetAttributes()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-88-a01693316a19> in <module>()
----> 1 b.GetAttributes()

C:\ProgramFiles\Python27\lib\site-packages\comtypes\automation.pyc in __ctypes_from_outparam__(self)
    440     def __ctypes_from_outparam__(self):
    441         # XXX Manual resource management, because of the VARIANT bug:
--> 442         result = self.value
    443         self.value = None
    444         return result

C:\ProgramFiles\Python27\lib\site-packages\comtypes\automation.pyc in _get_value(self, dynamic)
    391             return value
    392         elif self.vt & VT_ARRAY:
--> 393             typ = _vartype_to_ctype[self.vt & ~VT_ARRAY]
    394             return cast(self._.pparray, _midlSAFEARRAY(typ)).unpack()
    395         else:
```

Did some research on Google, but my knowledge of COM is just too low to help myself here..

**Comment by LiaungYip** [comment]
@thengineer : Your workaround using `win32com` is great.

**Comment by OndrejJanota** [comment]
Hi, I'm totally new in python (3 days) and I would like to create a program which rewrite block attributes. However, the script provided by thengineer (Here: https://gist.github.com/thengineer/7157510) doesn't work. I get this error (trying on Acad2017, drawing with only just one block with manualy defined block attribute):

Traceback (most recent call last):
  File "E:\Python\Programs\Autocad\Blockreference\block.py", line 21, in <module>
    HasAttributes = entity.HasAttributes() #  => tohle nějak nefunguje nevím proč
  File "E:\Python\lib\site-packages\win32com\client\__init__.py", line 473, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (repr(self), attr))
AttributeError: '<win32com.gen_py.AutoCAD/ObjectDBX Common 21.0 Type Library.IAcadEntity instance at 0x2236061099512>' object has no attribute 'HasAttributes'

Has anyone the same problem?
Thanks for the reply.

**Comment by Pilou59** [comment]
I've got the same issue, but using getattributes() method.

![image](https://user-images.githubusercontent.com/25279933/41820045-8dd270fc-77cb-11e8-8ab4-fc89f82d94f0.png)
Here are my investigations...

![image](https://user-images.githubusercontent.com/25279933/41820035-765cd282-77cb-11e8-92f0-ab4a1b0e7b10.png)

**Comment by thengineer** [comment]
Interestingly I came across the same issue a few months ago. I ended up checking the existence of attributes using python's `hasattr()` before accessing attributes.

**Comment by lam2912** [comment]
> I solved this by using win32com. In case anybody comes across the same problem (and wants to save a few hours of work): https://gist.github.com/thengineer/7157510

Please tell me: How to Setup Module Win 32???

**Comment by obook** [comment]
> > I solved this by using win32com. In case anybody comes across the same problem (and wants to save a few hours of work): https://gist.github.com/thengineer/7157510
> 
> Please tell me: How to Setup Module Win 32???

### Install the win32com Python library (pip version)

```bash
pip install pypiwin32
```
Then reboot !

### Usage

```python
import win32com.client
acad = win32com.client.Dispatch("AutoCAD.Application")

for entity in acad.ActiveDocument.ModelSpace:
            if entity.EntityName == 'AcDbBlockReference':
                print(entity.Name)
                if entity.HasAttributes:
                    for attrib in entity.GetAttributes():
                        print("-> {}: {}".format(attrib.TagString, attrib.TextString))
```

Regards.

**Comment by chuongmep** [comment]
Update for anyone need to quick check : 
```py
import win32com.client

# Connect to AutoCAD
acad = win32com.client.Dispatch("AutoCAD.Application")

# Define output file path
output_file = "block_attributes_output.txt"

# Open file for writing
with open(output_file, "w", encoding="utf-8") as f:
    for entity in acad.ActiveDocument.ModelSpace:
        if entity.EntityName == 'AcDbBlockReference':
            # Write block name, layer, and handle
            f.write(f"Block Name: {entity.Name}\n")
            f.write(f"Layer: {entity.Layer}\n")
            f.write(f"Handle: {entity.Handle}\n")

            # Write attributes if they exist
            if entity.HasAttributes:
                for attrib in entity.GetAttributes():
                    f.write(f"  -> {attrib.TagString}: {attrib.TextString}\n")

            f.write("\n")  # Blank line between blocks

print(f"Output saved to {output_file}")

```
